name: Bug Report
description: File a bug report
body:
  - type: input
    id: version
    attributes:
      label: What is your server version? Please use `/version` and paste the result here.
  - type: input
    id: project-version
    attributes:
      label: What is the current version you are using of this project?
  - type: textarea
    id: description
    attributes:
      label: What is the issue? How is it causing problems? How do you trigger this bug?
      placeholder: Describe the bug in detail
  - type: input
    id: frequency
    attributes:
      label: How often is this occurring?
      placeholder: How often is the bug happening, and how disruptive is it?
  - type: textarea
    id: solutions
    attributes:
      label: How would you like to see this fixed?
      placeholder: If you have any particular ideas for how this should be fixed, you can list them here