name: Bug Report
description: Something borked? Let us know.
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Plugin/Mod/Project Version
      placeholder: i.e. 1.3.2
    validations:
      required: true

  - type: input
    id: server_version
    attributes:
      label: Minecraft / Server Version
      placeholder: i.e. Paper 1.21.4
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What went wrong?
      description: Describe the issue in as much detail as you can.
      placeholder: Tell us what happened, what you expected, and what actually occurred.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How can we reproduce this?
      placeholder: Step-by-step instructions help a lot.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any error messages or server logs that might help.
      render: shell

  - type: textarea
    id: plugins
    attributes:
      label: Other Plugins
      description: Please paste your plugins list, datapack list, or mods list

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I’m using the latest version
        - label: I’ve checked the existing issues
