name: Feature Request
description: Suggest a new feature or improvement for this project.
labels: ["enhancement"]
body:

  - type: input
    id: version
    attributes:
      label: Plugin/Mod Version
      placeholder: i.e. 1.3.2

  - type: textarea
    id: request
    attributes:
      label: What would you like to see added or changed?
      placeholder: Describe the feature in your own words.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why do you want this feature?
      placeholder: What problem does this solve for you or your server?
      description: This helps us determine how useful the feature is overall.

  - type: textarea
    id: alternatives
    attributes:
      label: Have you tried any alternatives?
      placeholder: Other plugins? Workarounds? Server settings?

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I’ve checked if this feature already exists
        - label: I’ve checked other issues for duplicates
